// Minimal placeholder aws-exports so Amplify.configure won't fail during local dev.
// Replace with your real aws-exports generated by Amplify CLI when available.
const awsExports = {};
export default awsExports;
